version: '3.7'

services:
  ca.bc-coop.bclan:
    container_name: ca-bclan-network-it
    image: civisblockchain/bclan-ca:latest
    networks:
      - bclannet-it

  orderer.bclan:
    container_name: orderer-network-it
    image: civisblockchain/bclan-orderer:latest
    networks:
      - bclannet-it

  peer0.bc-coop.bclan:
    container_name: peer0-bclan-network-it
    image: civisblockchain/bclan-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=bclannet-it
    volumes:
      - /var/run/:/host/var/run/
    networks:
      - bclannet-it

  cli-init.bc-coop.bclan:
    container_name: cli-init-bclan-network-it
    image: civisblockchain/bclan-cli:latest
    command: /opt/blockchain-coop/util/init.sh
    networks:
      - bclannet-it

  coop-rest-java:
    container_name: coop-rest-bclan-network-it
    image: civisblockchain/bclan-coop-rest:latest
    environment:
      - coop_ccid=ssm
    ports:
      - 9090:9090
    networks:
      - bclannet-it

networks:
  bclannet-it:
    name: bclannet-it
